# Generated by Django 3.0 on 2021-07-23 17:07

from django.db import migrations, models
import django.db.models.deletion
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Поверховість',
                'verbose_name_plural': 'Поверховість',
            },
        ),
        migrations.AlterField(
            model_name='objectproperty',
            name='currency',
            field=models.ForeignKey(default=property.models.get_currency, on_delete=django.db.models.deletion.PROTECT, to='property.Currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='objectproperty',
            name='storeys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='property.Storey', verbose_name='Поверховість'),
        ),
    ]
