# Generated by Django 3.0 on 2021-08-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20210723_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='link_facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Посилання Facebook'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='link_instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Посилання Instagram'),
        ),
    ]
